import type { Metadata } from "next";
import type { Viewport } from "next";
import Footer from "@/components/layout/Footer";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  colorScheme: "light",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-[var(--color-brand-cream)] text-[var(--color-brand-black)]`}
    >
      <body className="min-h-full flex flex-col bg-[var(--color-brand-cream)] text-[var(--color-brand-black)]">
        {children}
        <Footer />
      </body>
    </html>
  );
}
